export default function Paises() {
    return [
        { sigla: 'br', nome: "Brasil" },
        { sigla: 'ar', nome: "Argentina" },
        { sigla: 'at', nome: "Austria" },
        { sigla: 'au', nome: "Australia" },
        { sigla: 'be', nome: "Belgium" },
        { sigla: 'bg', nome: "Bulgaria" },
        { sigla: 'ca', nome: "Canada" },
        { sigla: 'ch', nome: "Switzerland" },
        { sigla: 'cn', nome: "China" },
        { sigla: 'co', nome: "Colombia" },
        { sigla: 'cu', nome: "Cuba" },
        { sigla: 'cz', nome: "Czechia" },
        { sigla: 'de', nome: "Germany" },
        { sigla: 'eg', nome: "Egype" },
        { sigla: 'fr', nome: "France" },
        { sigla: 'gb', nome: "United Kingdom" },
        { sigla: 'gr', nome: "Greee" },
        { sigla: 'hk', nome: "Hong Kong" },
        { sigla: 'hu', nome: "Hungary" },
        { sigla: 'id', nome: "Indonesia" },
        { sigla: 'ie', nome: "Ireland" },
        { sigla: 'il', nome: "Israel" },
        { sigla: 'in', nome: "India" },
        { sigla: 'it', nome: "Italy" },
        { sigla: 'jp', nome: "Japan" },
        { sigla: 'kr', nome: "Korea" },
        { sigla: 'lt', nome: "Lithuania" },
        { sigla: 'lv', nome: "Latvia" },
        { sigla: 'ma', nome: "Morocco" },
        { sigla: 'mx', nome: "Mexico" },
        { sigla: 'my', nome: "Malaysia" },
        { sigla: 'ng', nome: "Nigeria" },
        { sigla: 'nl', nome: "Netherlands" },
        { sigla: 'no', nome: "Norway" },
        { sigla: 'nz', nome: "New Zealand" },
        { sigla: 'ph', nome: "Philippines" },
        { sigla: 'pl', nome: "Poland" },
        { sigla: 'pt', nome: "Portugal" },
        { sigla: 'ro', nome: "Romania" },
        { sigla: 'rs', nome: "Serbia" },
        { sigla: 'ru', nome: "Russia" },
        { sigla: 'sa', nome: "Saudi Arabia" },
        { sigla: 'se', nome: "Sweden" },
        { sigla: 'sg', nome: "Singapore" },
        { sigla: 'si', nome: "Slovenia" },
        { sigla: 'sk', nome: "Slovakia" },
        { sigla: 'th', nome: "Thailand" },
        { sigla: 'tr', nome: "Turkey" },
        { sigla: 'tw', nome: "Taiwan" },
        { sigla: 'ua', nome: "Ukraine" },
        { sigla: 'ae', nome: "United Arab Emirates" },
        { sigla: 'us', nome: "United States of America" },
        { sigla: 've', nome: "Venezuela" },
        { sigla: 'za', nome: "South Africa" }
    ]
}